builds:
    - binary: mapil
      goos:
          - darwin
          - linux
          - windows
      goarch:
          - amd64
          - arm64
      env:
          - CGO_ENABLED=0

release:
    prereleases: auto

universal_binaries:
    - replace: true

checksum:
    name_template: "checksum.txt"
